-- Seed data for testing
-- Note: These are example records - you should manually create users through your app
-- Actual user IDs will be generated by Supabase Auth

-- If you want to manually insert test data after creating users:
/*
INSERT INTO public.users (id, email, full_name, created_at)
VALUES 
  ('auth-user-id-1', 'test1@example.com', 'Test User 1', NOW()),
  ('auth-user-id-2', 'test2@example.com', 'Test User 2', NOW());
*/

-- Example SQL to query users:
-- SELECT * FROM public.users;

-- Example SQL to get user with auth data:
/*
SELECT 
  users.id,
  users.email,
  users.full_name,
  users.created_at,
  auth.users.confirmed_at,
  auth.users.last_sign_in_at
FROM 
  public.users
JOIN
  auth.users ON public.users.id = auth.users.id;
*/ 