[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio>=3.4.3",
    "fastapi>=0.115.12",
    "python-dotenv>=1.1.0",
    "sievedata>=1.5.0",
    "supabase>=2.15.2",
    "uvicorn>=0.34.2",
]
